name: Test

on:
  push:
    paths-ignore:
      - "docs"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs"
      - "**/*.md"

jobs:
  minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - luajit
          - luajit@v2.0
          - luajit@v2.0.5
          - luajit@871db2c84ecefd70a850e03a6c340214a81739f0
          - openresty
          - openresty@2.1-20231117.x
          - openresty@v2.1-20250117
          - openresty@dcc9c9ee67e1a5d3d636bd7745e95ddb4a1c70bc

        is-msvc:
          - true
          - false

        exclude:
          - os: ubuntu-latest
            is-msvc: true

          - os: macos-latest
            is-msvc: true

          - os: macos-latest
            lua-version: luajit@v2.0

          - os: macos-latest
            lua-version: luajit@v2.0.5

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup node 24
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24

      - name: Install packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup MSVC developer prompt
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        if: ${{ runner.os == 'Windows' && matrix.is-msvc }}

      - name: Install Lua
        uses: ./
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Display the Lua version
        run: lua -v

      - name: Test Lua
        run: lua -e "print('this is a test from ' .. _VERSION)"

      - name: Display LuaRocks version
        run: luarocks --version

      - name: Restore LuaFileSystem tarball
        id: restore-lfs-tarball
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: v1_8_0.tar.gz
          key: v1_8_0

      - name: Download LuaFileSystem tarball
        if: ${{ steps.restore-lfs-tarball.outputs.cache-hit != 'true' }}
        run: |
          curl -LO "https://github.com/lunarmodules/luafilesystem/archive/refs/tags/v1_8_0.tar.gz"

      - name: Save LuaFileSystem tarball
        if: ${{ steps.restore-lfs-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: v1_8_0.tar.gz
          key: v1_8_0

      - name: Extract LuaFileSystem
        run: tar -xf "v1_8_0.tar.gz"

      - name: Install LuaFileSystem
        working-directory: luafilesystem-1_8_0
        run: luarocks make "luafilesystem-scm-1.rockspec"

      # https://lunarmodules.github.io/luafilesystem/examples.html
      - name: Create a test file for LuaFileSystem
        shell: pwsh
        run: |
          $test_script = @'
          local lfs = require("lfs")

          function attrdir (path)
              for file in lfs.dir(path) do
                  if file ~= "." and file ~= ".." then
                      local f = path.."/"..file
                      print ("\t "..f)
                      local attr = lfs.attributes (f)
                      assert (type(attr) == "table")
                      if attr.mode == "directory" then
                          attrdir (f)
                      else
                          for name, value in pairs(attr) do
                              print (name, value)
                          end
                      end
                  end
              end
          end

          attrdir (".")
          '@

          Set-Content "lfs-test.lua" $test_script -NoNewLine

      - name: Test LuaFileSystem
        run: lua "lfs-test.lua"

      - name: Restore LuaSocket tarball
        id: restore-luasocket-tarball
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: v3.1.0.tar.gz
          key: v3.1.0

      - name: Download LuaSocket tarball
        if: ${{ steps.restore-luasocket-tarball.outputs.cache-hit != 'true' }}
        run: |
          curl -LO "https://github.com/lunarmodules/luasocket/archive/refs/tags/v3.1.0.tar.gz"

      - name: Save LuaSocket tarball
        if: ${{ steps.restore-luasocket-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: v3.1.0.tar.gz
          key: v3.1.0

      - name: Extract LuaSocket
        run: tar -xf "v3.1.0.tar.gz"

      - name: Install LuaSocket
        working-directory: luasocket-3.1.0
        run: luarocks make "rockspecs/luasocket-3.1.0-1.rockspec"

      - name: Test LuaSocket
        working-directory: luasocket-3.1.0/test
        run: lua hello.lua

      - name: Restore zlib tarball
        id: restore-zlib-tarball
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: zlib-1.3.1.tar.gz
          key: zlib-1.3.1

      - name: Download zlib tarball
        if: ${{ steps.restore-zlib-tarball.outputs.cache-hit != 'true' }}
        run: |
          curl -LO "https://zlib.net/fossils/zlib-1.3.1.tar.gz"

      - name: Save zlib tarball
        if: ${{ steps.restore-zlib-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: zlib-1.3.1.tar.gz
          key: zlib-1.3.1

      - name: Extract zlib
        run: tar -xf "zlib-1.3.1.tar.gz"

      - name: Build and install zlib, and configure it for LuaRocks
        shell: pwsh
        run: |
          if ("${{ runner.os }}" -eq "Windows") {
            if ($${{ matrix.is-msvc }}) {
              $generator = "NMake Makefiles";
            }
            else {
              $generator = "MinGW Makefiles";
            }
            $install_prefix = Join-Path -Path "${{ github.workspace }}" -ChildPath "external";
          }
          else {
            $generator = "Unix Makefiles";
            $install_prefix = Join-Path -Path "${{ github.workspace }}" -ChildPath "external";
          }

          cmake -G "${generator}" `
            "-DCMAKE_BUILD_TYPE=Release" `
            "-DBUILD_SHARED_LIBS=ON" `
            "--install-prefix" "${install_prefix}" `
            "-S" "zlib-1.3.1" `
            "-B" "build-zlib" && `
          cmake "--build" "build-zlib" "--config" "Release";

          if ($LASTEXITCODE -ne 0) {
            Write-Host "Failed to build zlib";
            exit 1;
          }

          cmake "--install" "build-zlib" "--config" "Release";

          $install_prefix_bin = Join-Path -Path "${install_prefix}" -ChildPath "bin";
          Add-Content "${{ github.path }}" "${install_prefix_bin}";
          luarocks config "variables.ZLIB_DIR" "${install_prefix}";

      - name: Restore lua-zlib tarball
        id: restore-lua-zlib-tarball
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: v1.3.tar.gz
          key: v1.3

      - name: Download lua-zlib tarball
        if: ${{ steps.restore-lua-zlib-tarball.outputs.cache-hit != 'true' }}
        run: |
          curl -LO "https://github.com/brimworks/lua-zlib/archive/refs/tags/v1.3.tar.gz"

      - name: Save lua-zlib tarball
        if: ${{ steps.restore-lua-zlib-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: v1.3.tar.gz
          key: v1.3

      - name: Extract lua-zlib
        run: tar -xf "v1.3.tar.gz"

      - name: Install lua-zlib
        working-directory: lua-zlib-1.3
        run: luarocks make "lua-zlib-scm-0.rockspec"

      - name: Test lua-zlib
        working-directory: lua-zlib-1.3
        run: lua test.lua