name: Test

on:
  push:
    paths-ignore:
      - "docs"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs"
      - "**/*.md"

jobs:
  minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - luajit
          - luajit@v2.0
          - luajit@v2.0.5
          - luajit@871db2c84ecefd70a850e03a6c340214a81739f0
          - openresty
          - openresty@2.1-20231117.x
          - openresty@v2.1-20250117
          - openresty@dcc9c9ee67e1a5d3d636bd7745e95ddb4a1c70bc

        is-msvc:
          - true
          - false

        exclude:
          - os: ubuntu-latest
            is-msvc: true

          - os: macos-latest
            is-msvc: true

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup node 24
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24

      - name: Install packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup MSVC developer prompt
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        if: ${{ runner.os == 'Windows' && matrix.is-msvc }}

      - name: Install Lua
        uses: ./
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Display the Lua version
        run: lua -v

      - name: Test Lua
        run: lua -e "print('this is a test from ' .. _VERSION)"

      - name: Display LuaRocks version
        run: luarocks --version

      - name: Install LuaFileSystem
        run: luarocks install luafilesystem

      # https://lunarmodules.github.io/luafilesystem/examples.html
      - name: Create a Test file for LuaFileSystem
        shell: pwsh
        run: |
          $test_script = @'
          local lfs = require"lfs"

          function attrdir (path)
              for file in lfs.dir(path) do
                  if file ~= "." and file ~= ".." then
                      local f = path..'/'..file
                      print ("\t "..f)
                      local attr = lfs.attributes (f)
                      assert (type(attr) == "table")
                      if attr.mode == "directory" then
                          attrdir (f)
                      else
                          for name, value in pairs(attr) do
                              print (name, value)
                          end
                      end
                  end
              end
          end

          attrdir (".")
          '@

          Set-Content "lfs-test.lua" $test_script -NoNewLine

      - name: Test LuaFileSystem
        run: lua "lfs-test.lua"