name: Test

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - 5.5
          - 5.4.7-rc4
          - luajit
          - luajit@v2.0
          - luajit@v2.0.5
          - luajit@871db2c84ecefd70a850e03a6c340214a81739f0
          - openresty
          - openresty@2.1-20231117.x
          - openresty@v2.1-20250117
          - openresty@dcc9c9ee67e1a5d3d636bd7745e95ddb4a1c70bc

        is-msvc:
          - true
          - false

        exclude:
          - os: ubuntu-latest
            is-msvc: true

          - os: macos-latest
            is-msvc: true

          - os: macos-latest
            lua-version: luajit@v2.0

          - os: macos-latest
            lua-version: luajit@v2.0.5

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup node 24
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24

      - name: Install packages (non-release branches)
        shell: pwsh
        run: |
          if ("${{ github.ref_name }}" -match "^release-(\d+)\.(\d+)\.(\d+)$")
          {
            Write-Host "Skipping the installation of packages on release branches.";
          }
          else
          {
            npm install
          }

      - name: Build (non-release branches)
        shell: pwsh
        run: |
          if ("${{ github.ref_name }}" -match "^release-(\d+)\.(\d+)\.(\d+)$")
          {
            Write-Host "Skipping the build on release branches.";
          }
          else
          {
            npm run build
          }

      - name: Setup MSVC developer prompt
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        if: ${{ runner.os == 'Windows' && matrix.is-msvc }}

      - name: Install Lua
        uses: ./
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Display the Lua version
        run: lua -v

      - name: Test Lua
        run: lua -e "print('this is a test from ' .. _VERSION)"

      - name: Display LuaRocks version
        run: luarocks --version

      - name: Display LuaRocks config
        run: luarocks config

      - name: Restore LuaFileSystem tarball
        id: restore-lfs-tarball
        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: v1_9_0.tar.gz
          key: v1_9_0

      - name: Download LuaFileSystem tarball
        if: ${{ steps.restore-lfs-tarball.outputs.cache-hit != 'true' }}
        run: |
          curl -LO "https://github.com/lunarmodules/luafilesystem/archive/refs/tags/v1_9_0.tar.gz"

      - name: Save LuaFileSystem tarball
        if: ${{ steps.restore-lfs-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: v1_9_0.tar.gz
          key: v1_9_0

      - name: Extract LuaFileSystem
        run: tar -xf "v1_9_0.tar.gz"

      - name: Install LuaFileSystem
        working-directory: luafilesystem-1_9_0
        run: luarocks make "luafilesystem-scm-1.rockspec"

      # https://lunarmodules.github.io/luafilesystem/examples.html
      - name: Create a test file for LuaFileSystem
        shell: pwsh
        run: |
          $test_script = @'
          local lfs = require("lfs")

          function attrdir (path)
              for file in lfs.dir(path) do
                  if file ~= "." and file ~= ".." then
                      local f = path.."/"..file
                      print ("\t "..f)
                      local attr = lfs.attributes (f)
                      assert (type(attr) == "table")
                      if attr.mode == "directory" then
                          attrdir (f)
                      else
                          for name, value in pairs(attr) do
                              print (name, value)
                          end
                      end
                  end
              end
          end

          attrdir (".")
          '@

          Set-Content "lfs-test.lua" $test_script -NoNewLine

      - name: Test LuaFileSystem
        run: lua "lfs-test.lua"

      - name: Restore LuaSocket tarball
        id: restore-luasocket-tarball
        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: v3.1.0.tar.gz
          key: v3.1.0

      - name: Download LuaSocket tarball
        if: ${{ steps.restore-luasocket-tarball.outputs.cache-hit != 'true' }}
        run: |
          curl -LO "https://github.com/lunarmodules/luasocket/archive/refs/tags/v3.1.0.tar.gz"

      - name: Save LuaSocket tarball
        if: ${{ steps.restore-luasocket-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: v3.1.0.tar.gz
          key: v3.1.0

      - name: Extract LuaSocket
        run: tar -xf "v3.1.0.tar.gz"

      - name: Install LuaSocket
        working-directory: luasocket-3.1.0
        run: luarocks make "rockspecs/luasocket-3.1.0-1.rockspec"

      - name: Test LuaSocket
        working-directory: luasocket-3.1.0/test
        run: lua hello.lua

      - name: Restore zlib tarball
        if: ${{ runner.os == 'Windows' }}
        id: restore-zlib-tarball
        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: zlib-1.3.1.tar.gz
          key: zlib-1.3.1

      - name: Download zlib tarball
        if: ${{ runner.os == 'Windows' && steps.restore-zlib-tarball.outputs.cache-hit != 'true' }}
        run: |
          curl -LO "https://zlib.net/fossils/zlib-1.3.1.tar.gz"

      - name: Save zlib tarball
        if: ${{ runner.os == 'Windows' && steps.restore-zlib-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: zlib-1.3.1.tar.gz
          key: zlib-1.3.1

      - name: Extract zlib
        if: ${{ runner.os == 'Windows' }}
        run: tar -xf "zlib-1.3.1.tar.gz"

      - name: Build and install zlib, and configure it for LuaRocks
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          if ($${{ matrix.is-msvc }}) {
            $cc = "cl";
            $generator = "NMake Makefiles";
          }
          else {
            $cc = "gcc";
            $generator = "MinGW Makefiles";
          }
          $install_prefix = Join-Path -Path "${{ github.workspace }}" -ChildPath "external";

          cmake -G "${generator}" `
            "-DCMAKE_C_COMPILER=${cc}" `
            "-DCMAKE_BUILD_TYPE=Release" `
            "-DBUILD_SHARED_LIBS=ON" `
            "--install-prefix" "${install_prefix}" `
            "-S" "zlib-1.3.1" `
            "-B" "build-zlib" && `
          cmake "--build" "build-zlib" "--config" "Release" && `
          cmake "--install" "build-zlib" "--config" "Release";

          $install_prefix_bin = Join-Path -Path "${install_prefix}" -ChildPath "bin";
          Add-Content "${{ github.path }}" "${install_prefix_bin}";
          luarocks config "variables.ZLIB_DIR" "${install_prefix}";

      - name: Restore lua-zlib tarball
        id: restore-lua-zlib-tarball
        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: v1.3.tar.gz
          key: v1.3

      - name: Download lua-zlib tarball
        if: ${{ steps.restore-lua-zlib-tarball.outputs.cache-hit != 'true' }}
        run: |
          curl -LO "https://github.com/brimworks/lua-zlib/archive/refs/tags/v1.3.tar.gz"

      - name: Save lua-zlib tarball
        if: ${{ steps.restore-lua-zlib-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: v1.3.tar.gz
          key: v1.3

      - name: Extract lua-zlib
        run: tar -xf "v1.3.tar.gz"

      - name: Patch lua-zlib rockspec to build on Lua 5.5+
        shell: pwsh
        run: |
          if ("${{ matrix.lua-version }}" -match "^(\d+)\.(\d+)(\.\d+)?$")
          {
            $major = [int]::Parse($Matches[1]);
            $minor = [int]::Parse($Matches[2]);

            if ([System.Version]::new("${{ matrix.lua-version }}") -ge [System.Version]::new("5.5"))
            {
              $rockspecTxt = (Get-Content "lua-zlib-scm-0.rockspec") -replace "5.4", "${major}.${minor}";
              Set-Content "lua-zlib-scm-0.rockspec" $rockspecTxt -NoNewline;
              Write-Host "lua-zlib rockspec patched to build on ${{ matrix.lua-version }}";
            }
            else
            {
              Write-Host "There is no need to patch lua-zlib for this Lua version";
            }
          }
          else
          {
            Write-Host "There is no need to patch lua-zlib for this Lua version";
          }

      - name: Install lua-zlib
        working-directory: lua-zlib-1.3
        run: luarocks make "lua-zlib-scm-0.rockspec"

      - name: Test lua-zlib
        working-directory: lua-zlib-1.3
        run: lua test.lua

  ubuntu-different-cc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - 5.5
          - 5.4.7-rc4

        cc:
          - g++
          - clang
          - clang++

        include:
          - lua-version: luajit
            cc: clang

          - lua-version: luajit@v2.0
            cc: clang

          - lua-version: openresty
            cc: clang

          - lua-version: openresty@v2.1-20250117
            cc: clang

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup node 24
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24

      - name: Install clang
        if: ${{ startsWith(matrix.cc, 'clang') }}
        run: sudo apt install -y clang

      - name: Install packages (non-release branches)
        shell: pwsh
        run: |
          if ("${{ github.ref_name }}" -match "^release-(\d+)\.(\d+)\.(\d+)$")
          {
            Write-Host "Skipping the installation of packages on release branches.";
          }
          else
          {
            npm install
          }

      - name: Build (non-release branches)
        shell: pwsh
        run: |
          if ("${{ github.ref_name }}" -match "^release-(\d+)\.(\d+)\.(\d+)$")
          {
            Write-Host "Skipping the build on release branches.";
          }
          else
          {
            npm run build
          }

      - name: Install Lua (${{ matrix.cc }})
        uses: ./
        with:
          cc: ${{ matrix.cc }}
          ld: ${{ matrix.cc }}
          lua-version: ${{ matrix.lua-version }}

      - name: Display the Lua version
        run: lua -v

      - name: Test Lua
        run: lua -e "print('this is a test from ' .. _VERSION)"

      - name: Display LuaRocks version
        run: luarocks --version

      - name: Display LuaRocks config
        run: luarocks config